[package]
name = "cons_proc_macros"
version = "0.1.0"
authors = ["Josh Palmer <jpalmerwatkins@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.60" }
proc-macro2 = "1.0.24"